export const PLANNING_PRODUCTIVITY_TARGET_EUR_PER_HOUR = 50;
export const PLANNING_PRODUCTIVITY_TARGET_CENTS_PER_HOUR =
  PLANNING_PRODUCTIVITY_TARGET_EUR_PER_HOUR * 100;

export const PLANNING_PAYROLL_RATIO_TARGET_PERCENT = 35;
export const PLANNING_PAYROLL_RATIO_TARGET = PLANNING_PAYROLL_RATIO_TARGET_PERCENT / 100;